backend = "glx";

shadow=false;
full-shadow = true;
corner-radius=8;
animations = (
	
	# Play shrinking (disappear) animation when a window is closed or hidden
	{
		triggers = [ "close", "hide" ];
		preset = "disappear";
		scale = 0.9;
		duration = 0.1;
	},
	
	# Play a growing (appear) animation when a window is opened or revealed (shown)
	{
		triggers = [ "open", "show" ];
		preset = "appear";
		scale = 0.9;
		duration = 0.1;
	},

	# When a window is moved or resized, animate the geometry
	{
		triggers = [ "geometry" ];
		preset = "geometry-change";
		duration = 0.1;
	}
);


rules = (

	{
		match = " I3_FLOATING_WINDOW@:c=1 && window_type!='notification' ";
		shadow = true;
		shadow-offset-y = 100;
	},

	{
		match = "window_type = 'utility' || window_type = 'popup_menu' || window_type = 'dnd'";
		shadow = false;
		corner-radius = 0;
		# full-shadow = true;
	},

	{
		match = "role = 'PictureInPicture'";
		shadow = true;
		corner-radius = 8;
	},

	{
		match = "window_type = 'dnd'";
		shadow = false;
		corner-radius = 0;
	},

	@include "addition/polybar.conf",
	@include "addition/rofi.conf",
	@include "addition/rofi.conf",
	@include "addition/fullscreen.conf",
	@include "addition/tty-clock.conf",

);
