# Workspace gestures (3 finger)
# Note: Pressing shift while swipping does the same as super+ctrl+shift+DIRECTION (moving view+window)
gesture swipe left  3   xdotool key super+ctrl+Left
gesture swipe up    3   xdotool key super+ctrl+Up
gesture swipe right 3   xdotool key super+ctrl+Right
gesture swipe down  3   xdotool key super+ctrl+Down

# Window gestures (4 finger)
gesture swipe up    4   xdotool key super+shift+Up
gesture swipe down  4   xdotool key super+shift+Down
gesture swipe left  4   xdotool key super+shift+Left
gesture swipe right 4   xdotool key super+shift+Right

gesture pinch in    3   $HOME/.config/i3/script/libinput-gestures.sh in 3
gesture pinch out   3   $HOME/.config/i3/script/libinput-gestures.sh out 3

gesture pinch in    4   $HOME/.config/i3/script/libinput-gestures.sh in 4
gesture pinch out   4   $HOME/.config/i3/script/libinput-gestures.sh out 4

