bindsym Print exec $HOME/.config/i3/script/screenshot.sh

bindsym XF86MonBrightnessDown --release exec --no-startup-id $HOME/.config/i3/script/brightness.sh down
bindsym XF86MonBrightnessUp --release exec --no-startup-id $HOME/.config/i3/script/brightness.sh up
exec $HOME/.config/i3/script/brightness.sh max

bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioPlay exec playerctl play-pause
exec_always --no-startup-id $HOME/.config/i3/script/cap-volume.sh

bindsym $alt+XF86AudioLowerVolume exec playerctl previous
bindsym $alt+XF86AudioRaiseVolume exec playerctl next

exec $HOME/.config/i3/script/numlock.sh on
