exec $HOME/.config/i3/script/lock-screen.sh

bindsym $mod+l exec $HOME/.config/i3/script/lock-screen.sh
bindsym --release XF86PowerOff exec $HOME/.config/i3/script/lock-screen.sh

# Auto sleep after 60sec
exec_always xset s 60 +dpms
