set $i3lock i3lock -t \
	-i $HOME/Wallpapers/lock/Townscaper-Island.png \
	--clock \
	--time-str="%H:%M" \
	--time-color=FFFFFFFF \
	--time-font="JetBrains Mono:style=Bold" \
	--time-size=60 \
	--time-pos="x+w/2-170:y+h/2-160" \
	--time-size=60 \
	--date-str=""
exec $i3lock
bindsym $mod+l exec $i3lock
bindsym --release XF86PowerOff exec $i3lock

# Auto sleep after 60sec
exec_always xset s 60 +dpms
