bindsym           $mod+space     exec rofi -show drun
bindsym --release $alt+Tab       exec rofi -show window
bindsym --release XF86Calculator exec rofi -show calc

bindsym           $mod+Return    exec alacritty

