# DEFAULTS COLOURS:
# 
# class                     border  background text    indicator child_border
# client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
# client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
# client.unfocused        #333333 #222222 #888888 #292d2e   #222222
# client.urgent           #2f343a #900000 #ffffff #900000   #900000
# client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
# client.background       #ffffff

default_border pixel 0
font pango:monospace 0

gaps outer 0px
gaps inner 8px

client.focused           #4c7899 #285577    #ffffff #4e7b31   #285577
client.focused_inactive  #4c7899 #285577    #ffffff #4e7b31   #285577
client.unfocused         #4c7899 #285577    #ffffff #4e7b31   #285577
client.urgent            #4c7899 #285577    #ffffff #4e7b31   #285577
client.placeholder       #4c7899 #285577    #ffffff #4e7b31   #285577
client.background        #ffffff

# focus_follows_mouse no
mouse_warping none

popup_during_fullscreen all

