# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+Ctrl+1 workspace number $ws1
bindsym $mod+Ctrl+2 workspace number $ws2
bindsym $mod+Ctrl+3 workspace number $ws3
bindsym $mod+Ctrl+4 workspace number $ws4
bindsym $mod+Ctrl+5 workspace number $ws5
bindsym $mod+Ctrl+6 workspace number $ws6
bindsym $mod+Ctrl+7 workspace number $ws7
bindsym $mod+Ctrl+8 workspace number $ws8
bindsym $mod+Ctrl+9 workspace number $ws9
bindsym $mod+Ctrl+0 workspace number $ws10
bindsym $mod+Ctrl+grave exec $HOME/.config/i3/script/empty-workspace.sh set

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10
bindsym $mod+Shift+grave exec $HOME/.config/i3/script/empty-workspace.sh move

bindsym $mod+Ctrl+Shift+1 move container to workspace number $ws1; workspace number $ws1
bindsym $mod+Ctrl+Shift+2 move container to workspace number $ws2; workspace number $ws2
bindsym $mod+Ctrl+Shift+3 move container to workspace number $ws3; workspace number $ws3
bindsym $mod+Ctrl+Shift+4 move container to workspace number $ws4; workspace number $ws4
bindsym $mod+Ctrl+Shift+5 move container to workspace number $ws5; workspace number $ws5
bindsym $mod+Ctrl+Shift+6 move container to workspace number $ws6; workspace number $ws6
bindsym $mod+Ctrl+Shift+7 move container to workspace number $ws7; workspace number $ws7
bindsym $mod+Ctrl+Shift+8 move container to workspace number $ws8; workspace number $ws8
bindsym $mod+Ctrl+Shift+9 move container to workspace number $ws9; workspace number $ws9
bindsym $mod+Ctrl+Shift+0 move container to workspace number $ws10; workspace number $ws10
bindsym $mod+Ctrl+Shift+grave exec $HOME/.config/i3/script/empty-workspace.sh both

bindsym $mod+Ctrl+Left workspace prev
bindsym $mod+Ctrl+Right workspace next
bindsym $mod+Ctrl+shift+Left move to workspace prev; workspace prev
bindsym $mod+ctrl+shift+Right move to workspace next; workspace next
bindsym $mod+Ctrl+space floating toggle; sticky toggle

