[bar/main]
monitor = ${env:MONITOR:}
width = 100%
height = 42px
radius = 8px
background = ${colors.background}
foreground = ${colors.foreground}
border-top-size = 8px
border-left-size = 8px
border-right-size = 8px
border-color = #00000000
padding-left = 2
padding-right = 2
module-margin = 1
separator = "|"
separator-foreground = ${colors.disabled}
font-0 = "Symbols Nerd Font:size=11;2"
font-1 = "JetBrains Mono:size=10;2"
font-2 = "Noto Emoji:size=11;2"
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
screenchange-reload = true
modules-left = rofi xworkspaces xwindow
modules-center = date playerctl
modules-right = pulseaudio backlight wlan tailscale info-stats battery-bluetooth battery

[module/rofi]
type = custom/text
format = <label>
label = %{A:rofi -show drun:}%{F#4E7B31}%{F-}%{A}

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces
group-by-monitor = true
format= <label-monitor> <label-state>
pin-workspaces = true
label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1
label-monitor = %name%

[module/xwindow]
type = internal/xwindow

label = %{A:rofi -show window:}%title:0:60:...%%{A}
; label-maxlen=60

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
interval = 5
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
label-muted = "%{F#4E7B31} %{F-}%percentage%%"
ramp-volume-foreground = ${colors.primary}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/battery-bluetooth]
type = custom/script
exec = ~/.config/polybar/script/battery-bluetooth.sh
interval = 5

[module/playerctl]
type = custom/script
exec = ~/.config/polybar/script/playerctl.sh
tail = true

[module/info-stats]
type = custom/script
exec = ~/.config/polybar/script/stats.sh
tail = true
click-left = "kill -USR1 $(pgrep --oldest --parent %pid%)"

[module/memory]
type = internal/memory
interval = 5
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/temperature]
type = internal/temperature
interval = 5
format = <label>
format-warn = <label-warn>
format-prefix = "TEMP "
format-warn-prefix = "TEMP "
format-prefix-foreground = ${colors.primary}
format-warn-prefix-foreground = ${colors.primary}
label = %temperature-c%
label-warn = ⚠ %temperature-c%
thermal-zone = 0

[module/tailscale]
type = custom/script
exec = ~/.config/polybar/script/tailscale.sh
tail = true
format-prefix = "%{A:alacritty --title 'Tailscale' --command tsui:}󱗼%{A} "
format-prefix-foreground = ${colors.primary}

[module/wlan]
type = internal/network
interface-type = wireless
interval = 5
format-connected = %{A:alacritty --title 'NetworkManager TUI' --command 'nmtui':}<ramp-signal> <label-connected>%{A}
format-disconnected = %{A:alacritty --title 'NetworkManager TUI' --command 'nmtui':}<label-disconnected>%{A}
label-connected = "%essid% (%local_ip%)"
label-disconnected = %{F#4E7B31}󰤮%{F-} none
ramp-signal-foreground = ${colors.primary}
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤨

[module/date]
type = internal/date
interval = 5
date = %{F#4E7B31} %{F-}%H:%M
date-alt = %{F#4E7B31} %{F-}%Y/%b/%d (%a)
label = %date%
label-foreground = ${colors.foreground}

[module/battery]
type = internal/battery
full-at = 100
low-at = 25
battery = BAT1
adapter = ACAD
poll-interval = 5
format-charging = %{F#4E7B31}󱐋%{F-} <ramp-capacity> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = %{F#4E7B31}󱁖%{F-} <ramp-capacity> <label-full>
format-low = %{F#4E7B31}%{F-} <ramp-capacity> <label-low>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%
ramp-capacity-foreground = ${colors.primary}
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

[module/backlight]
type = internal/backlight
use-actual-brightness = false
enable-scroll = true
scroll-interval = 5
format = <ramp> <label>
label = %percentage%%
ramp-foreground = ${colors.primary}
ramp-0 = 󱩎
ramp-1 = 󱩏
ramp-2 = 󱩐
ramp-3 = 󱩑
ramp-4 = 󱩒
ramp-5 = 󱩓
ramp-6 = 󱩔
ramp-7 = 󱩕
ramp-8 = 󱩖
ramp-9 = 󰛨
