[module/internal/network]
type = internal/network
interface-type = wireless

interval = 1

format-connected = %{A:alacritty --title 'NetworkManager TUI' --command 'nmtui':}<ramp-signal> <label-connected>%{A}
format-disconnected = %{A:alacritty --title 'NetworkManager TUI' --command 'nmtui':}<label-disconnected>%{A}

label-connected = %essid%
; label-connected = %essid% (IPv4=%local_ip%) (IPv6=%local_ip6%) (MAC=%mac%)

label-disconnected = %{F#4E7B31}󰤮%{F-} none

ramp-signal-foreground = ${colors.primary}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤨
